package com.dariomatias.my_commerce.controller;

import com.dariomatias.my_commerce.dto.ApiResult;
import com.dariomatias.my_commerce.dto.analytics.TotalRevenueResponseDTO;
import com.dariomatias.my_commerce.dto.analytics.UniqueCustomersResponseDTO;
import com.dariomatias.my_commerce.model.User;
import com.dariomatias.my_commerce.service.AnalyticsService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.util.UUID;

@RestController
@RequestMapping("/api/analytics")
@Tag(
        name = "Analytics",
        description = "Endpoints related to sales, revenue, and customer analytics"
)
public class AnalyticsController {

    private final AnalyticsService service;

    public AnalyticsController(AnalyticsService service) {
        this.service = service;
    }

    @Operation(
            summary = "Get unique customers for current user",
            description = "Returns the number of unique customers associated with the authenticated user's stores."
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Unique customers retrieved successfully",
                    content = @Content(schema = @Schema(implementation = UniqueCustomersResponseDTO.class))
            ),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
    })
    @GetMapping("/me/stats/unique-customers")
    @PreAuthorize("hasAnyRole('ADMIN', 'SUBSCRIBER')")
    public ResponseEntity<ApiResult<UniqueCustomersResponseDTO>> getUniqueCustomers(
            @AuthenticationPrincipal User user
    ) {
        return ResponseEntity.ok(
                ApiResult.success(
                        "Unique customers retrieved successfully.",
                        service.getUniqueCustomers(user.getId())
                )
        );
    }

    @Operation(
            summary = "Get total revenue for current user",
            description = "Returns the total revenue generated by the authenticated user's stores."
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Total revenue retrieved successfully",
                    content = @Content(schema = @Schema(implementation = TotalRevenueResponseDTO.class))
            ),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
    })
    @GetMapping("/me/stats/total-revenue")
    @PreAuthorize("hasAnyRole('ADMIN', 'SUBSCRIBER')")
    public ResponseEntity<ApiResult<TotalRevenueResponseDTO>> getTotalRevenue(
            @AuthenticationPrincipal User user
    ) {
        return ResponseEntity.ok(
                ApiResult.success(
                        "Total revenue retrieved successfully.",
                        service.getTotalRevenue(user.getId())
                )
        );
    }

    @Operation(
            summary = "Get unique customers by store",
            description = "Returns the number of unique customers for a specific store."
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Store unique customers retrieved successfully",
                    content = @Content(schema = @Schema(implementation = UniqueCustomersResponseDTO.class))
            ),
            @ApiResponse(responseCode = "404", description = "Store not found"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
    })
    @GetMapping("/store/{storeId}/stats/unique-customers")
    @PreAuthorize("hasAnyRole('ADMIN', 'SUBSCRIBER')")
    public ResponseEntity<ApiResult<UniqueCustomersResponseDTO>> getUniqueCustomersByStore(
            @PathVariable UUID storeId
    ) {
        return ResponseEntity.ok(
                ApiResult.success(
                        "Store unique customers retrieved successfully.",
                        service.getUniqueCustomersByStore(storeId)
                )
        );
    }

    @Operation(
            summary = "Get total revenue by store",
            description = "Returns the total revenue generated by a specific store."
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Store total revenue retrieved successfully",
                    content = @Content(schema = @Schema(implementation = TotalRevenueResponseDTO.class))
            ),
            @ApiResponse(responseCode = "404", description = "Store not found"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
    })
    @GetMapping("/store/{storeId}/stats/total-revenue")
    @PreAuthorize("hasAnyRole('ADMIN', 'SUBSCRIBER')")
    public ResponseEntity<ApiResult<TotalRevenueResponseDTO>> getTotalRevenueByStore(
            @PathVariable UUID storeId
    ) {
        return ResponseEntity.ok(
                ApiResult.success(
                        "Store total revenue retrieved successfully.",
                        service.getTotalRevenueByStore(storeId)
                )
        );
    }

    @Operation(
            summary = "Get global total revenue",
            description = "Returns the total revenue generated across all stores. Admin access only."
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Global total revenue retrieved successfully",
                    content = @Content(schema = @Schema(implementation = TotalRevenueResponseDTO.class))
            ),
            @ApiResponse(responseCode = "403", description = "Forbidden")
    })
    @GetMapping("/total-revenue")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<ApiResult<TotalRevenueResponseDTO>> getTotalRevenue() {
        BigDecimal totalRevenue = service.getTotalRevenue();

        return ResponseEntity.ok(
                ApiResult.success(
                        "Global total revenue retrieved successfully.",
                        new TotalRevenueResponseDTO(totalRevenue)
                )
        );
    }
}
